#!/usr/bin/env python3
from pystyle import Colors, Colorate
import subprocess
import json
import sys 
import os

HOME = os.path.dirname(os.path.abspath(__file__))

def load_theme():
    try:
        with open(os.path.join(HOME, 'theme.json'), 'r') as file:
            data = json.load(file)
            return data.get("theme", "rainbow") 
    except FileNotFoundError:
        return "rainbow" 

def install_true(key_to_update):
    check_path = os.path.join(HOME, 'check.json')
    with open(check_path, 'r') as file:
        data = json.load(file)
    if key_to_update in data.get('tools', {}) and data['tools'][key_to_update] is False:
        data['tools'][key_to_update] = True
    with open(check_path, 'w') as file:
        json.dump(data, file, indent=4)

def check_install(filename='check.json'):
    filepath = os.path.join(HOME, filename) 
    with open(filepath, 'r') as f:
        data = json.load(f)
    return data

def tool_installed(tool_id):
    tools_status = check_install()
    return tools_status['tools'].get(tool_id, False)

def install_tool(tool_sh):
    script_path = os.path.join(HOME, 'tools', tool_sh) 
    try:
        with subprocess.Popen(['bash', script_path], stdout=subprocess.PIPE, text=True) as process:
            while True:
                output = process.stdout.readline()
                if output == '' and process.poll() is not None:
                    break
                if output:
                    print(output.strip())
    except FileNotFoundError:
        print(f" The script '{script_path}' was not found.")
    except Exception as e:
        print(f" An unexpected error occurred: {e}")

def recon_ng():
    if tool_installed("1"):
        try:
            print(Colors.yellow + "Executing Recon-ng...")
            print(Colors.cyan + "Type 'exit' to exit.")
            subprocess.run(['recon-ng']) 
            sys.exit() 
        except Exception as e:
            print(f"An error occurred while running the script: {e}")
    else:
        install_option = input(Colors.green + " Recon-ng is not installed. Install now? (y/n):\n >>> ")
        install_option = install_option.strip().lower()
        if install_option == 'y':
            tool_sh = 'recon-ng.sh'
            install_tool(tool_sh)
            install_true("1")
            input(Colors.green + " Press Enter to run script.\n >>> ")
            recon_ng()
        elif install_option == 'n':
            main()
        else:
            print(Colors.green + " Invalid choice. Enter 'y' or 'n'.\n >>> ")
            recon_ng()


def nikto():
    if tool_installed("2"):
        try:
            print(Colors.yellow + "Starting shell in ./tools/nikto/program \nCtrl+C once to stop operations within shell and then 'exit' to exit.")
            print(Colors.cyan + "Example Usage: perl nikto.pl -h http://www.example.com")
            os.chdir(os.path.join(HOME, 'tools', 'nikto', 'program'))
            subprocess.call(['bash']) 
            sys.exit() 
        except Exception as e:
            print(f"An error occurred while running the script: {e}")
    else:
        install_option = input(Colors.green + " Nikto is not installed. Install now? (y/n):\n >>> ")
        install_option = install_option.strip().lower()
        if install_option == 'y':
            tool_sh = 'nikto.sh'
            install_tool(tool_sh)
            install_true("2")
            input(Colors.green + " Press Enter to run script.\n >>> ")
            nikto()
        elif install_option == 'n':
            main()
        else:
            print(Colors.green + " Invalid choice. Enter 'y' or 'n'.\n >>> ")
            nikto()
                    
def dns_recon():
    if tool_installed("3"):
        try:
            print(Colors.yellow + "Executing DNSrecon... ")
            print(Colors.cyan + "Example Usage: dnsrecon -d website.com")
            subprocess.run(['dnsrecon']) 
            sys.exit() 
        except Exception as e:
            print(f"An error occurred while running the script: {e}")
    else:
        install_option = input(Colors.green + " DNSrecon is not installed. Install now? (y/n):\n >>> ")
        install_option = install_option.strip().lower()
        if install_option == 'y':
            tool_sh = 'dnsrecon.sh'
            install_tool(tool_sh)
            install_true("3")
            input(Colors.green + " Press Enter to run script.\n >>> ")
            dns_recon()
        elif install_option == 'n':
            main()
        else:
            print(Colors.green + " Invalid choice. Enter 'y' or 'n'.\n >>> ")
            dns_recon()

def udpscan():
    if tool_installed("4"):
        print(Colors.cyan + "Make a selection: ")
        udpscan_choice = input(Colors.cyan + "\n[1] Prompt mode \n[2] CLI mode \n   >>>   ")
        if udpscan_choice == '1':             
            try:
                print(Colors.yellow + "Executing UDPSCAN... ")
                print(Colors.cyan + "Ctrl+C to exit.")
                os.chdir(os.path.join(HOME, 'tools', 'UDPSCAN'))
                subprocess.run(['python3','UDPSCAN.py']) 
                sys.exit() 
            except Exception as e:
                print(f"An error occurred while running the script: {e}")
        elif udpscan_choice == '2':
            try:
                print(Colors.yellow + "Starting shell in ./tools/UDPSCAN ")
                print(Colors.yellow + "Type 'exit' to exit. ")
                os.chdir(os.path.join(HOME, 'tools', 'UDPSCAN'))
                subprocess.run(['python3','UDPSCAN.py','-h']) 
                subprocess.call(['bash'])
                sys.exit() 
            except Exception as e:
                print(f"An error occurred while running the script: {e}")
        else: 
            print(Colors.red + "Invalid choice. Enter 1 or 2.")
            udpscan()
    else:
        install_option = input(Colors.green + " UDPSCAN is not installed. Install now? (y/n):\n >>> ")
        install_option = install_option.strip().lower()
        if install_option == 'y':
            tool_sh = 'UDPSCAN.sh'
            install_tool(tool_sh)
            install_true("4")
            input(Colors.green + " Press Enter to run script.\n >>> ")
            udpscan()
        elif install_option == 'n':
            main()
        else:
            print(Colors.green + " Invalid choice. Enter 'y' or 'n'.\n >>> ")
            udpscan()
            
def infoga():
    if tool_installed("5"):
        try:
            print(Colors.yellow + "Starting shell in ./tools/Infoga-py3 \nType 'exit' to exit.")
            print(Colors.cyan + "Example Usage: python3 infoga.py --target website.com --source all")
            os.chdir(os.path.join(HOME, 'tools', 'Infoga-py3'))
            subprocess.run(['python3','infoga.py']) 
            subprocess.call(['bash']) 
            sys.exit() 
        except Exception as e:
            print(f"An error occurred while running the script: {e}")
    else:
        install_option = input(Colors.green + " Infoga is not installed. Install now? (y/n):\n >>> ")
        install_option = install_option.strip().lower()
        if install_option == 'y':
            tool_sh = 'infoga.sh'
            install_tool(tool_sh)
            install_true("5")
            input(Colors.green + " Press Enter to run script.\n >>> ")
            infoga()
        elif install_option == 'n':
            main()
        else:
            print(Colors.green + " Invalid choice. Enter 'y' or 'n'.\n >>> ")
            infoga()

def blackbird():
    if tool_installed("6"):
        try:
            print(Colors.yellow + "\nStarting shell in ./tools/blackbird-iSH \nCtrl+C to stop script, then 'exit' to exit shell. ")
            print(Colors.cyan + "Set up AI: python3 blackbird.py --setup-ai")
            print(Colors.cyan + "Example Usage: python3 blackbird.py --username johndoe --ai")
            os.chdir(os.path.join(HOME, 'tools', 'blackbird-iSH'))
            print(Colors.green)
            subprocess.run(['python3','blackbird.py']) 
            subprocess.call(['bash']) 
            sys.exit() 
        except Exception as e:
            print(f"An error occurred while running the script: {e}")
    else:
        install_option = input(Colors.green + " BlackBird is not installed. Install now? (y/n):\n >>> ")
        install_option = install_option.strip().lower()
        if install_option == 'y':
            tool_sh = 'blackbird.sh'
            install_tool(tool_sh)
            install_true("6")
            input(Colors.green + " Press Enter to run script.\n >>> ")
            blackbird()
        elif install_option == 'n':
            main()
        else:
            print(Colors.green + " Invalid choice. Enter 'y' or 'n'.\n >>> ")
            blackbird()

def nosint():
    if tool_installed("7"):
        try:
            print(Colors.yellow + "\nStarting shell in ./tools/nosint \nCtrl+C to stop script and exit shell. ")
            os.chdir(os.path.join(HOME, 'tools', 'nosint'))
            print(Colors.green)
            subprocess.run(['python3','nosint']) 
            subprocess.call(['bash']) 
            sys.exit() 
        except Exception as e:
            print(f"An error occurred while running the script: {e}")
    else:
        install_option = input(Colors.green + " NoSint is not installed. Install now? (y/n):\n >>> ")
        install_option = install_option.strip().lower()
        if install_option == 'y':
            tool_sh = 'nosint.sh'
            install_tool(tool_sh)
            install_true("7")
            input(Colors.green + " Press Enter to run script.\n >>> ")
            nosint()
        elif install_option == 'n':
            main()
        else:
            print(Colors.green + " Invalid choice. Enter 'y' or 'n'.\n >>> ")
            nosint()

def intel_base():
    if tool_installed("8"):
        try:
            print(Colors.yellow + "\nStarting shell in ./tools/IntelBase-CLI \nUse option 3 to exit program, then type 'exit' to exit shell.")
            print(Colors.green + "")
            os.chdir(os.path.join(HOME, 'tools', 'IntelBase-CLI'))
            subprocess.run(['python3','intelbase.py']) 
            subprocess.call(['bash']) 
            sys.exit() 
        except Exception as e:
            print(f"An error occurred while running the script: {e}")
    else:
        install_option = input(Colors.green + " IntelBase is not installed. Install now? (y/n):\n >>> ")
        install_option = install_option.strip().lower()
        if install_option == 'y':
            tool_sh = 'intelbase.sh'
            install_tool(tool_sh)
            install_true("8")
            input(Colors.green + " Press Enter to run script.\n >>> ")
            intel_base()
        elif install_option == 'n':
            main()
        else:
            print(Colors.green + " Invalid choice. Enter 'y' or 'n'.\n >>> ")
            intel_base()

def xsstrike():
    if tool_installed("9"):
        try:
            print(Colors.yellow + "\nStarting shell in ./tools/XSStrike \nType 'exit' to exit.")
            print(Colors.cyan + """Example Usage: python3 xsstrike.py -u "http://example.com/vulnerable.php?param=test" -o results.txt \n""")
            print(Colors.green + "")
            os.chdir(os.path.join(HOME, 'tools', 'XSStrike'))
            subprocess.run(['python3','xsstrike.py']) 
            subprocess.call(['bash']) 
            sys.exit() 
        except Exception as e:
            print(f"An error occurred while running the script: {e}")
    else:
        install_option = input(Colors.green + " XSStrike is not installed. Install now? (y/n):\n >>> ")
        install_option = install_option.strip().lower()
        if install_option == 'y':
            tool_sh = 'xsstrike.sh'
            install_tool(tool_sh)
            install_true("9")
            input(Colors.green + " Press Enter to run script.\n >>> ")
            xsstrike()
        elif install_option == 'n':
            main()
        else:
            print(Colors.green + " Invalid choice. Enter 'y' or 'n'.\n >>> ")
            xsstrike()

def openssl():
    if tool_installed("13"):
        try:
            print(Colors.yellow + "\nStarting shell... \nType 'exit' to exit.")
            print(Colors.green + "")
            subprocess.run(['openssl','help']) 
            subprocess.call(['bash']) 
            sys.exit() 
        except Exception as e:
            print(f"An error occurred while running the script: {e}")
    else:
        install_option = input(Colors.green + " OpenSSL is not installed. Install now? (y/n):\n >>> ")
        install_option = install_option.strip().lower()
        if install_option == 'y':
            tool_sh = 'openssl.sh'
            install_tool(tool_sh)
            install_true("13")
            input(Colors.green + " Press Enter to run script.\n >>> ")
            openssl()
        elif install_option == 'n':
            main()
        else:
            print(Colors.green + " Invalid choice. Enter 'y' or 'n'.\n >>> ")
            openssl()
            
def gnupg():
    if tool_installed("14"):
        try:
            print(Colors.yellow + "\nStarting shell... \nType 'exit' to exit.")
            print(Colors.green + "")
            subprocess.run(['gpg','-h']) 
            subprocess.call(['bash']) 
            sys.exit() 
        except Exception as e:
            print(f"An error occurred while running the script: {e}")
    else:
        install_option = input(Colors.green + " GnuPG is not installed. Install now? (y/n):\n >>> ")
        install_option = install_option.strip().lower()
        if install_option == 'y':
            tool_sh = 'gnupg.sh'
            install_tool(tool_sh)
            install_true("14")
            input(Colors.green + " Press Enter to run script.\n >>> ")
            gnupg()
        elif install_option == 'n':
            main()
        else:
            print(Colors.green + " Invalid choice. Enter 'y' or 'n'.\n >>> ")
            gnupg()

def install_all():
    tools_dir = os.path.join(HOME, 'tools')
    subprocess.run(['bash', 'all.sh'], cwd=tools_dir, check=True)
    for i in range(1, 15):
        install_true(str(i))
    input(Colors.green + " >>> ")
    main()

def zipbrute(): 
    if tool_installed("11"):
        try:
            print(Colors.yellow + "\nStarting shell in ./tools/FileBruteforcers \nCtrl+C to exit shell.")
            print(Colors.green + "")
            os.chdir(os.path.join(HOME, 'tools', 'FileBruteforcers'))
            subprocess.run(['python3','zipbrute.py']) 
            subprocess.call(['bash']) 
            sys.exit() 
        except Exception as e:
            print(f"An error occurred while running the script: {e}")
    else:
        install_option = input(Colors.green + " FileBruteForcers is not installed. Install now? (y/n):\n >>> ")
        install_option = install_option.strip().lower()
        if install_option == 'y':
            tool_sh = 'filebruteforcers.sh'
            install_tool(tool_sh)
            install_true("11")
            install_true("12")
            input(Colors.green + " Press Enter to run script.\n >>> ")
            zipbrute()
        elif install_option == 'n':
            main()
        else:
            print(Colors.green + " Invalid choice. Enter 'y' or 'n'.\n >>> ")
            zipbrute() 

def pdfbrute(): 
    if tool_installed("12"):
        try:
            print(Colors.yellow + "\nStarting shell in ./tools/FileBruteforcers \nCtrl+C to exit shell.")
            print(Colors.green + "")
            os.chdir(os.path.join(HOME, 'tools', 'FileBruteforcers'))
            subprocess.run(['python3','pdfbrute.py']) 
            subprocess.call(['bash']) 
            sys.exit() 
        except Exception as e:
            print(f"An error occurred while running the script: {e}")
    else:
        install_option = input(Colors.green + " FileBruteForcers is not installed. Install now? (y/n):\n >>> ")
        install_option = install_option.strip().lower()
        if install_option == 'y':
            tool_sh = 'filebruteforcers.sh'
            install_tool(tool_sh)
            install_true("11")
            install_true("12")
            input(Colors.green + " Press Enter to run script.\n >>> ")
            pdfbrute()
        elif install_option == 'n':
            main()
        else:
            print(Colors.green + " Invalid choice. Enter 'y' or 'n'.\n >>> ")
            pdfbrute()  

def sqlmap(): 
    if tool_installed("10"):
        try:
            print(Colors.yellow + "Starting shell in ./tools/sqlmap-dev \nType 'exit' to exit.")
            print(Colors.cyan + """Example Usage: python3 sqlmap.py -u "http://192.168.1.250/?p=1&forumaction=search" --dbs """)
            os.chdir(os.path.join(HOME, 'tools', 'sqlmap-dev'))
            subprocess.run(['python3','sqlmap.py','-h']) 
            subprocess.call(['bash']) 
            sys.exit() 
        except Exception as e:
            print(f"An error occurred while running the script: {e}")
    else:
        install_option = input(Colors.green + " sqlmap is not installed. Install now? (y/n):\n >>> ")
        install_option = install_option.strip().lower()
        if install_option == 'y':
            tool_sh = 'sqlmap.sh'
            install_tool(tool_sh)
            install_true("10")
            input(Colors.green + " Press Enter to run script.\n >>> ")
            sqlmap()
        elif install_option == 'n':
            main()
        else:
            print(Colors.green + " Invalid choice. Enter 'y' or 'n'.\n >>> ")
            sqlmap()

def choose_theme():
    theme = load_theme()
    subprocess.run(['clear'])
    theme_menu = """ 
██╗███████╗██╗  ██╗   ████████╗ ██████╗  ██████╗ ██╗     ███████╗
╚═╝██╔════╝██║  ██║   ╚══██╔══╝██╔═══██╗██╔═══██╗██║     ██╔════╝
██║███████╗███████║█████╗██║   ██║   ██║██║   ██║██║     ███████╗
██║╚════██║██╔══██║╚════╝██║   ██║   ██║██║   ██║██║     ╚════██║
██║███████║██║  ██║      ██║   ╚██████╔╝╚██████╔╝███████╗███████║
╚═╝╚══════╝╚═╝  ╚═╝      ╚═╝    ╚═════╝  ╚═════╝ ╚══════╝╚══════╝
                                                  v1.0.1
                                                
╔══════════════════════════════════════════════════════════════╗
║                          <Themes>                            ║
╠═════════════════════════════╦════════════════════════════════╣
║      <Dark Mode Only>       ║        <Light Mode Only>       ║
╠═════════════════════════════╬════════════════════════════════╣
║     [1] white               ║     [8] black                  ║
║     [2] white_to_red        ║     [9] black_to_red           ║
║     [3] red_to_white        ║     [10] red_to_black          ║
║     [4] white_to_green      ║     [11] black_to_green        ║
║     [5] green_to_white      ║     [12] green_to_black        ║
║     [6] white_to_blue       ║     [13] black_to_blue         ║
║     [7] blue_to_white       ║     [14] blue_to_black         ║
╠═════════════════════════════╩════════════════════════════════╣
║                          <Colors>                            ║
╠═════════════════════════════╦════════════════════════════════╣
║     [15] red                ║     [24] turquoise             ║
║     [16] green              ║     [25] light_gray            ║
║     [17] blue               ║     [26] dark_gray             ║
║     [18] gray               ║     [27] light_red             ║
║     [19] yellow             ║     [28] light_green           ║
║     [20] purple             ║     [29] light_blue            ║
║     [21] cyan               ║     [30] dark_red              ║
║     [22] orange             ║     [31] dark_green            ║
║     [23] pink               ║     [32] dark_blue             ║
╠═════════════════════════════╩════════════════════════════════╣
║                         <Gradients>                          ║
╠═════════════════════════════╦════════════════════════════════╣
║     [33] red_to_yellow      ║     [42] cyan_to_blue          ║
║     [34] yellow_to_red      ║     [43] blue_to_purple        ║
║     [35] red_to_purple      ║     [44] purple_to_blue        ║
║     [36] purple_to_red      ║     [45] red_to_blue           ║
║     [37] green_to_yellow    ║     [46] blue_to_red           ║
║     [38] yellow_to_green    ║     [47] red_to_green          ║
║     [39] green_to_cyan      ║     [48] green_to_red          ║
║     [40] cyan_to_green      ║     [49] green_to_blue         ║
║     [41] blue_to_cyan       ║     [50] blue_to_green         ║
║                             ║     [51] rainbow               ║
╠═════════════════════════════╩════════════════════════════════╣
║ Type 'm' to go back to menu.                                 ║
╚══════════════════════════════════════════════════════════════╝"""
    themes = {
    '1': 'white',     
    '2': 'white_to_red',
    '3': 'red_to_white',
    '4': 'white_to_green',
    '5': 'green_to_white',
    '6': 'white_to_blue',
    '7': 'blue_to_white',
    '8': 'black',     
    '9': 'black_to_red',
    '10': 'red_to_black',
    '11': 'black_to_green',
    '12': 'green_to_black',
    '13': 'black_to_blue',
    '14': 'blue_to_black',
    '15': 'red', 
    '16': 'green', 
    '17': 'blue',
    '18': 'gray',
    '19': 'yellow', 
    '20': 'purple', 
    '21': 'cyan',
    '22': 'orange', 
    '23': 'pink', 
    '24': 'turquoise',
    '25': 'light_gray', 
    '26': 'dark_gray',
    '27': 'light_red', 
    '28': 'light_green', 
    '29': 'light_blue',
    '30': 'dark_red', 
    '31': 'dark_green', 
    '32': 'dark_blue',   
    '33': 'red_to_yellow',
    '34': 'yellow_to_red',
    '35': 'red_to_purple',
    '36': 'purple_to_red',
    '37': 'green_to_yellow',
    '38': 'yellow_to_green',
    '39': 'green_to_cyan',
    '40': 'cyan_to_green',
    '41': 'blue_to_cyan',
    '42': 'cyan_to_blue',
    '43': 'blue_to_purple',
    '44': 'purple_to_blue',
    '45': 'red_to_blue',
    '46': 'blue_to_red',
    '47': 'red_to_green',
    '48': 'green_to_red',
    '49': 'green_to_blue',
    '50': 'blue_to_green',
    '51': 'rainbow'
}
    single_colors = [
        'white', 'black', 'red', 'green', 'blue', 'yellow', 
        'purple', 'cyan', 'orange', 'pink', 'turquoise', 
        'light_gray', 'dark_gray', 'gray', 'light_red', 
        'light_green', 'light_blue', 'dark_red', 'dark_green', 
        'dark_blue'
    ]
    
    while True:
        try:
            color = getattr(Colors, theme, None)
            if color is None:
                raise ValueError(f"Color '{theme}' not found.")
            is_single_color = theme in single_colors
            if is_single_color:
                print(color + theme_menu) 
            else:
                print(Colorate.Vertical(color, theme_menu, 1))  
        except Exception:
            input(Colors.red + "Error: Invalid color attribute for the current theme. Press Enter to reload.\n   >>>   ")
            choose_theme()  
            break
        theme_choice = input(Colors.green + " └──> ").strip().lower()        
        if theme_choice in themes:
            selected_theme = themes[theme_choice]
            try:
                with open(os.path.join(HOME, 'theme.json'), 'w') as file:
                    json.dump({"theme": selected_theme}, file)
                choose_theme()  
                break
            except IOError as e:
                print(Colors.red + f"An error occurred while saving the theme: {e}")
                break 
        elif theme_choice == '52':
            warning = input(Colors.red+ "You found glitched theme easter egg! \nGlitching will persist after exiting /breaking script. \nType 'exit' in terminal to stop. Continue? (y/n) \n   >>>   ").strip().lower()
            if warning == 'y':
                selected_theme = "reset"
                try:
                    with open(os.path.join(HOME, 'theme.json'), 'w') as file:
                        json.dump({"theme": selected_theme}, file)
                    choose_theme()  
                    break
                except IOError as e:
                    print(Colors.red + f"An error occurred while saving the theme: {e}")
                    break
            else: 
                choose_theme() 
                            
        elif theme_choice == "m":
            main() 
            break        
        else:
            input(Colors.red + "Invalid option, press Enter to try again.\n   >>>   ")
                                    
def help_menu():
    theme = load_theme()
    subprocess.run(['clear'])
    helpscreen = r"""
██╗███████╗██╗  ██╗   ████████╗ ██████╗  ██████╗ ██╗     ███████╗
╚═╝██╔════╝██║  ██║   ╚══██╔══╝██╔═══██╗██╔═══██╗██║     ██╔════╝
██║███████╗███████║█████╗██║   ██║   ██║██║   ██║██║     ███████╗
██║╚════██║██╔══██║╚════╝██║   ██║   ██║██║   ██║██║     ╚════██║
██║███████║██║  ██║      ██║   ╚██████╔╝╚██████╔╝███████╗███████║
╚═╝╚══════╝╚═╝  ╚═╝      ╚═╝    ╚═════╝  ╚═════╝ ╚══════╝╚══════╝
                                                  v1.0.1
╔══════════════════════════════════════════════════════════════╗
║                           <Help>                             ║
╠══════════════╦═══════════════════════════════════════════════╣
║     Tool     ║                 Documentation                 ║
╠══════════════╬═══════════════════════════════════════════════╣
║ Recon-ng     ║ https://github.com/lanmaster53/recon-ng/wiki  ║
╠══════════════╬═══════════════════════════════════════════════╣
║ Nikto        ║ https://github.com/sullo/nikto/wiki           ║
╠══════════════╬═══════════════════════════════════════════════╣
║              ║ https://github.com/darkoperator/dnsrecon      ║
║ DNSrecon     ╠═══════════════════════════════════════════════╣
║              ║ https://tinyurl.com/DNSrecon-cheat-sheet      ║
╠══════════════╬═══════════════════════════════════════════════╣
║ UDPSCAN      ║ https://github.com/cons0le7/UDPSCAN           ║
╠══════════════╬═══════════════════════════════════════════════╣
║ Infoga       ║ https://github.com/The404Hacking/Infoga       ║
╠══════════════╬═══════════════════════════════════════════════╣
║ BlackBird    ║ https://github.com/cons0le7/blackbird-iSH     ║
╠══════════════╬═══════════════════════════════════════════════╣
║ NoSint       ║ https://github.com/cons0le7/nosint            ║
╠══════════════╬═══════════════════════════════════════════════╣
║ IntelBase    ║ https://github.com/cons0le7/IntelBase-CLI     ║
╠══════════════╬═══════════════════════════════════════════════╣
║ XSStrike     ║ https://github.com/s0md3v/XSStrike/wiki/Usage ║
╠══════════════╬═══════════════════════════════════════════════╣
║ sqlmap       ║ https://github.com/sqlmapproject/sqlmap       ║
╠══════════════╬═══════════════════════════════════════════════╣
║ OpenSSL      ║ https://docs.openssl.org/master               ║
╠══════════════╬═══════════════════════════════════════════════╣
║ GnuPG        ║ https://www.gnupg.org/documentation           ║
╠══════════════╬═══════════════════════════════════════════════╣
║ ZipBrute     ║ github.com/midwestcoder2020/FileBruteforcers  ║
╠══════════════╬═══════════════════════════════════════════════╣
║ PDFBrute     ║ github.com/midwestcoder2020/FileBruteforcers  ║
╠══════════════╩═══════════════════════════════════════════════╣
║ Type 'm' to go back to menu.                                 ║
╚══════════════════════════════════════════════════════════════╝"""
    while True:
        color = getattr(Colors, theme, None)
        is_single_color = theme in [
        'white', 'black', 'red', 'green', 'blue', 'yellow', 
        'purple', 'cyan', 'orange', 'pink', 'turquoise', 
        'light_gray', 'dark_gray', 'gray', 'light_red', 
        'light_green', 'light_blue', 'dark_red', 'dark_green', 
        'dark_blue'
        ]

        if is_single_color:
            print(color + helpscreen) 
        else:
            print(Colorate.Vertical(color, helpscreen, 1))  
        option_2 = input(Colors.green + " └──> ").strip().lower()
        if option_2 == 'm':
            main() 
            break
        else:
            input(Colors.red + "\n\n\nInvalid option, press Enter to try again. \n\n   >>>   ")
            
def report_issue():
    print(Colors.yellow + "\nOpen an issue at: \nhttps://github.com/cons0le7/iSH-tools/issues")
    input(Colors.green + """
    

    
            
 >>> """)
    main() 
    
def main():
    theme = load_theme()
    subprocess.run(['clear'])
    banner = """
██╗███████╗██╗  ██╗   ████████╗ ██████╗  ██████╗ ██╗     ███████╗
╚═╝██╔════╝██║  ██║   ╚══██╔══╝██╔═══██╗██╔═══██╗██║     ██╔════╝
██║███████╗███████║█████╗██║   ██║   ██║██║   ██║██║     ███████╗
██║╚════██║██╔══██║╚════╝██║   ██║   ██║██║   ██║██║     ╚════██║
██║███████║██║  ██║      ██║   ╚██████╔╝╚██████╔╝███████╗███████║
╚═╝╚══════╝╚═╝  ╚═╝      ╚═╝    ╚═════╝  ╚═════╝ ╚══════╝╚══════╝
                                                  v1.0.1
╔══════════════════════════════════════════════════════════════╗
║                https://github.com/cons0le7                   ║
╠═════════════════════════════╦════════════════════════════════╣
║  Reconnaissance             ║  Password Cracking             ║
║      ├── [1] Recon-ng       ║      ├── [11] ZipBrute (FBF)   ║
║      ├── [2] Nikto          ║      └── [12] PDFBrute (FBF)   ║
║      ├── [3] DNSrecon       ║                                ║
║      └── [4] UDPSCAN        ║  Cryptography                  ║
║                             ║      ├── [13] OpenSSL          ║
║  OSINT                      ║      └── [14] GnuPG            ║
║      ├── [5] Infoga         ║                                ║
║      ├── [6] BlackBird      ║  Options                       ║
║      ├── [7] NoSint *       ║      ├── [i] Install All       ║
║      └── [8] IntelBase *    ║      ├── [t] Themes            ║
║                             ║      ├── [x] Exit              ║
║  Web-App Testing            ║      ├── [?] Help              ║
║      ├── [9] XSStrike       ║      └── [!] Report an Issue   ║
║      └── [10] sqlmap        ║                                ║
╠═════════════════════════════╩════════════════════════════════╣
║ * = API token required [$]                                   ║
╚══════════════════════════════════════════════════════════════╝"""
    color = getattr(Colors, theme, None)
    is_single_color = theme in [
        'white', 'black', 'red', 'green', 'blue', 'yellow', 
        'purple', 'cyan', 'orange', 'pink', 'turquoise', 
        'light_gray', 'dark_gray', 'gray', 'light_red', 
        'light_green', 'light_blue', 'dark_red', 'dark_green', 
        'dark_blue'
    ]
    if is_single_color:
        print(color + banner) 
    else:
        print(Colorate.Vertical(color, banner, 1))
    options = {
        "1": recon_ng,
        "2": nikto,
        "3": dns_recon,
        "4": udpscan,
        "5": infoga,
        "6": blackbird,
        "7": nosint,
        "8": intel_base,
        "9": xsstrike,
        "10": sqlmap,
        "11": zipbrute,
        "12": pdfbrute, 
        "13": openssl,
        "14": gnupg,
        "t": choose_theme,
        "i": install_all,
        "?": help_menu,
        "h": help_menu,
        "!": report_issue
    }    
    while True:
        option = input(Colors.green + " └──> ").strip().lower()
        if option in options:
            options[option]()
            break
        elif option == "x": 
            subprocess.call(['clear'])
            sys.exit()
        else:
            input(Colors.red + "Invalid option, press Enter to try again. \n   >>>   ")
            main()

main()
